### ISSUE TITLE
Scala string match error

### ISSUE THREAD

**Issue by marameg** [lbruand/cql2plantuml#3]
@lbruand , This implementation is a really nice idea! I am trying to use it for a project and was not able to execute the jar file successfully. Please see the error below:

~: java -jar cql2plantuml-assembly-1.0.jar gf_is_rollup.cql 
 gf_is_rollup.cql gfroll.puml
Exception in thread "main" scala.MatchError: [1.1] failure: string matching regex `(?i)\QCREATE TYPE\E' expected but `' found

^ (of class scala.util.parsing.combinator.Parsers$Failure)
	at net.deeppay.cqlAST2puml.Main$.main(Main.scala:48)
	at net.deeppay.cqlAST2puml.Main.main(Main.scala)

It is creating a puml file of 0 bytes because of this error. Can you please advice a workaround or correct this?

**Comment by lbruand** [comment]
Hi,

Thx :+1: 
Any chance that you can provide the cql file that you are using ?
Or a smaller version that still has that problem ?
What is the charset that you are using in that file ?
It really looks like this is a charset encoding problem ...

Best regards,
Lucas

**Comment by marameg** [comment]
Thanks for your quick response Lucas! After you pointed out, I checked my cql file and for some reason it had special characters at the start of the file which were hidden when i used cat to read the file but I was able to see them in vi mode. Anyways it is solved now. Sorry for the bother and thanks for this code!

**Comment by lbruand** [comment]
No worries. Really glad to hear this tool helped you.
